# Generated by Django 3.2.5 on 2021-07-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'worst'), (2, 'Bad'), (3, 'Not_Bad'), (4, 'Excellent'), (5, 'Good')]),
        ),
    ]
